---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnatroutetables.networking.wag.tools
spec:
  group: networking.wag.tools
  names:
    kind: XNatRouteTable
    plural: xnatroutetables
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  name:
                    type: string
                  vpcId:
                    type: string
                  natId:
                    type: string
                required:
                - name
                - vpcId
                - natId
            required:
            - parameters
          status:
            type: object
            properties:
              routeTableId:
                type: string
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: natroutetables
  labels:
    crossplane.io/xrd: xnatroutetables.networking.wag.tools
    provider: aws-provider
spec:
  compositeTypeRef:
    apiVersion: networking.wag.tools/v1alpha1
    kind: XNatRouteTable
  resources:
  - name: routetable
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: RouteTable
      metadata:
        name: ""
        labels:
          routetable: ""
      spec:
        providerConfigRef:
          name: aws-provider
        forProvider:
          region: eu-central-1
          vpcId: ""
          tags:
            Name: ""
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.name
      toFieldPath: spec.forProvider.tags.Name
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.name
      toFieldPath: metadata.labels[crossplane.io/claim-name]
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.name
      toFieldPath: metadata.labels[routetable]
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.vpcId
      toFieldPath: spec.forProvider.vpcId
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.id
      toFieldPath: status.routeTableId
  - name: natroute
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: Route
      metadata:
        name: route-nat
      spec:
        providerConfigRef:
          name: aws-provider
        forProvider:
          destinationCidrBlock: 0.0.0.0/0
          region: eu-central-1
          natGatewayId: ""
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: status.routeTableId
      toFieldPath: spec.forProvider.routeTableId
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.natId
      toFieldPath: spec.forProvider.natGatewayId